# Generated by Django 2.1.2 on 2018-10-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181030_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activateprofile',
            name='key',
            field=models.IntegerField(max_length=124),
        ),
    ]
