# Generated by Django 2.1.2 on 2018-10-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181031_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activateprofile',
            name='key',
            field=models.CharField(max_length=124),
        ),
    ]
