# Generated by Django 2.1.2 on 2018-11-08 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('last_name', models.CharField(default='', max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors')),
                ('biography', models.CharField(blank=True, default='', max_length=5000)),
                ('birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActorComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Actor')),
            ],
        ),
    ]
