# Generated by Django 2.1.2 on 2018-11-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='original_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
