# Generated by Django 2.1.2 on 2018-11-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='birth',
            new_name='born',
        ),
        migrations.AddField(
            model_name='actor',
            name='died',
            field=models.DateField(blank=True, null=True),
        ),
    ]
