# Generated by Django 2.1.2 on 2018-11-25 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actors', '0002_actor_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorcomment',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actorcomment',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_comments', to='actors.Actor'),
        ),
        migrations.AlterField(
            model_name='actorcomment',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
