# Generated by Django 2.1.2 on 2018-11-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20181110_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='if_died',
            field=models.BooleanField(default=False),
        ),
    ]
