# Generated by Django 2.1.2 on 2018-11-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20181108_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorcomment',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
