# Generated by Django 2.1.2 on 2018-11-11 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_actor_if_died'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='city_of_birth',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='place_of_birth',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='died',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='if_died',
            field=models.BooleanField(default=False, verbose_name='cross if dead'),
        ),
        migrations.AlterField(
            model_name='actorcomment',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='actors.Actor'),
        ),
    ]
