# Generated by Django 2.1.2 on 2018-11-08 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20181108_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorcomment',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
