# Generated by Django 2.1.2 on 2018-11-19 21:02

import actors.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20181118_1539'),
        ('actors', '0004_auto_20181119_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=actors.models.ActorRole.upload_path)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actors.Actor')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
