# Generated by Django 2.1.2 on 2018-11-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_auto_20181111_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='city_of_birth',
            new_name='nationality',
        ),
    ]
