# Generated by Django 2.1.2 on 2018-11-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_actorcomment_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorcomment',
            name='edited_date',
            field=models.DateField(auto_now=True),
        ),
    ]
