# Generated by Django 2.1.2 on 2018-11-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_auto_20181127_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('last_name', 'name')},
        ),
    ]
