# Generated by Django 2.1.2 on 2018-11-19 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_actorrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorrole',
            name='actor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actor_role', to='actors.Actor'),
        ),
        migrations.AlterField(
            model_name='actorrole',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie_role', to='movies.Movie'),
        ),
    ]
