# Generated by Django 2.1.2 on 2018-11-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_auto_20181127_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='is_crew',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Is also crew member? (i.e. director, composer sountrack, costume designer)'),
        ),
        migrations.AlterField(
            model_name='crewrole',
            name='role',
            field=models.CharField(choices=[('Director', 'Director'), ('Producer', 'Producer'), ('Set Designer', 'Set Designer'), ('Costume Designer', 'Costume Designer'), ('Prop Master', 'Prop Master'), ('Makeup Artist', 'Makeup Artist'), ('Movie Editor', 'Movie Editor'), ('Other', 'Other')], max_length=100),
        ),
    ]
