# Generated by Django 2.1.2 on 2018-11-11 12:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_auto_20181111_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='place_of_birth',
        ),
        migrations.AddField(
            model_name='actor',
            name='city_of_birth',
            field=models.CharField(default=24, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
