# Generated by Django 2.1.2 on 2018-11-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_auto_20181111_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorgallery',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_gallery', to='actors.Actor'),
        ),
    ]
