# Generated by Django 2.1.2 on 2018-11-19 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_auto_20181119_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorrole',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_role', to='movies.Movie'),
        ),
    ]
