# Generated by Django 2.1.2 on 2018-12-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_auto_20181127_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewrole',
            name='actor',
            field=models.ForeignKey(limit_choices_to={'is_crew': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_crew_role', to='actors.Actor'),
        ),
    ]
