# Generated by Django 2.1.2 on 2018-11-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_auto_20181119_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actorrole',
            options={'ordering': ('actor', 'movie')},
        ),
    ]
