# Generated by Django 2.1.2 on 2018-11-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0007_auto_20181109_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorcomment',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actorcomment',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
