# Generated by Django 2.1.2 on 2018-11-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0008_auto_20181109_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorcomment',
            name='comment',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
