# Generated by Django 2.1.2 on 2018-11-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0008_auto_20181119_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('last_name', 'name')},
        ),
    ]
