# Generated by Django 2.1.2 on 2018-11-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0010_auto_20181109_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorcomment',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
