# Generated by Django 2.1.2 on 2018-11-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0011_auto_20181109_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorcomment',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
