# Generated by Django 2.1.2 on 2018-11-12 18:52

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('year_of_production', models.PositiveSmallIntegerField()),
                ('production', django_countries.fields.CountryField(max_length=2)),
                ('budget', models.PositiveIntegerField(help_text='in dollars')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=movies.models.Movie.upload_path)),
                ('duration', models.PositiveSmallIntegerField(help_text='in minutes')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_category', to='movies.Movie')),
            ],
        ),
    ]
