# Generated by Django 2.1.2 on 2018-11-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecategory',
            name='related_movie',
            field=models.ManyToManyField(related_name='movie_category', to='movies.Movie'),
        ),
    ]
