# Generated by Django 2.1.2 on 2018-12-13 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20181129_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(help_text='in dollars', validators=[django.core.validators.MaxValueValidator(400000000, 'The maximum value is 400000000 dollars.')]),
        ),
    ]
