# Generated by Django 2.1.2 on 2018-11-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviecomment_moviegallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='Action', max_length=50),
            preserve_default=False,
        ),
    ]
