# Generated by Django 2.1.2 on 2018-11-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20181115_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
