# Generated by Django 2.1.2 on 2018-11-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecategory',
            name='movie',
        ),
        migrations.DeleteModel(
            name='MovieCategory',
        ),
    ]
