# Generated by Django 2.1.2 on 2018-11-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20181115_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='comment',
            field=models.TextField(blank=True, help_text='150 character maximum.', max_length=150, null=True),
        ),
    ]
